version: '2'
services:
  redis-cluster:
    image: grokzen/redis-cluster:4.0.2
    volumes:
      # optional
      - ./server/redisCluster/data:/data
      - ./server/redisCluster/redis-conf:/redis-conf
#      - ./server/redisCluster/redis-data:/redis-data
    environment:
      IP: 0.0.0.0
    ports:
      # master nodes
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      # slave nodes
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"