version: '2'
services:
    elk:
        container_name: elk
        image: sebp/elk:624
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
        volumes:
            - ./server/elk/elk-data:/var/lib/elasticsearch


