version: '2'
services:
    nginx:
        container_name: nginx
        image: nginx:1.13.12
        ports:
            - "80:80"
        volumes:
            - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./server/nginx/conf:/etc/nginx/conf
            - ./server/nginx/logs:/logs
            - ./manager-h5:/usr/src/manager-h5
            - ./pc-dhb168:/usr/src/pc-dhb168
        stdin_open: true
        tty: true
        links:
          - php-fpm
    php-fpm:
        container_name: php-fpm
        image: php-fmp-5.6
#        build:
#            context: server/php/php-fpm/5.6/
        ports:
            - "9000:9000"
        volumes:
             #- /etc/localtime:/etc/localtime:ro
             #- /etc/timezone:/etc/timezone:ro
             - ./manager-h5:/usr/src/manager-h5
             - ./pc-dhb168:/usr/src/pc-dhb168
             - ./server/php/php-fpm/5.6/php-fpm.d:/usr/local/etc/php-fpm.d
             - ./server/php/php-fpm/5.6/fpm-php.www.log:/var/log/fpm-php.www.log
        stdin_open: true
        tty: true
        links:
            - redis
            - mysql
        depends_on:
            - redis
            - mysql

    redis:
         container_name: redis
         image: redis:4.0.2
         ports:
            - "6379:6379"
         volumes:
            - ./server/redis/redis.conf:/etc/redis/redis.conf
            - ./server/redis/data:/data
            - ./server/redis/logs:/logs
            - ./server/redis/redis_cache:/redis_cache
    mysql:
        container_name: mysql
        image: mysql:5.7.22
        ports:
            - "3306:3306"
        volumes:
            - ./server/mysql/data:/var/lib/mysql
            - ./server/mysql/logs:/logs
            - ./server/mysql/my.cnf:/etc/my.cnf
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: manager

        stdin_open: true
        tty: true
    node:
        container_name: node
        image: node
        volumes:
            - ./manager-h5:/usr/src/manager-h5
        stdin_open: true
        tty: true